allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

buildscript {
    ext {
        compileSdkVersion = 35   // REQUIRED by plugins
        targetSdkVersion  = 30   // Android 11
        minSdkVersion     = 21
    }
}


rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
